name: smart_eshop
description: A mini e‑commerce app (“Smart EShop”) built with Provider, SharedPreferences, and glassmorphism design.
publish_to: "none" # this is a local project

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.0.5

  # Persistent storage
  shared_preferences: ^2.0.15

  # HTTP client for RESTful API
  http: ^0.13.5

  # Badge on cart icon
  badges: ^2.0.3

  # Display rating stars
  flutter_rating_bar: ^4.0.0

  # SVG support (if needed for icons/logos)
  flutter_svg: ^1.1.6

  # iOS-style icons
  cupertino_icons: ^1.0.2
  
  slide_to_act: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
